<%@ page contentType="text/html;charset=UTF-8" %>
<%@ page import="java.util.List,model.Product,model.Category,model.User,model.Role" %>
<% User u=(User)session.getAttribute("user"); if(u==null||u.getRole()!=Role.ADMIN){response.sendRedirect(request.getContextPath()+"/login.jsp");return;} List<Product> ps=(List<Product>)request.getAttribute("products"); List<Category> cs=(List<Category>)request.getAttribute("categories"); String err=request.getParameter("error"); %>
<!doctype html><html><head><title>Manage Products</title><style>body{font-family:Arial;max-width:1200px;margin:30px auto;padding:20px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ddd;padding:8px}input,select{padding:6px}.inline{display:inline}</style></head><body>
<h1>Manage Products</h1><p><a href="<%=request.getContextPath()%>/admin.jsp">← Admin</a></p><%if(err!=null){%><p style="color:red"><%=err%></p><%}%>
<h2>Add Product</h2><form action="<%=request.getContextPath()%>/admin-products" method="post"><input type="hidden" name="action" value="add"><input name="name" placeholder="Name" required><input name="price" type="number" step=".01" min="0" placeholder="Price" required><input name="stock" type="number" min="0" placeholder="Stock" required><select name="categoryId" required><%for(Category c:cs){%><option value="<%=c.getId()%>"><%=c.getName()%></option><%}%></select><button>Add Product</button></form>
<h2>Products</h2><table><tr><th>ID</th><th>Name</th><th>Price</th><th>Stock</th><th>Category</th><th>Actions</th></tr>
<%for(Product p:ps){String f="p"+p.getId();%><tr><td><%=p.getId()%></td><td><input form="<%=f%>" name="name" value="<%=p.getName()%>" required></td><td><input form="<%=f%>" name="price" type="number" step=".01" min="0" value="<%=p.getPrice()%>" required></td><td><input form="<%=f%>" name="stock" type="number" min="0" value="<%=p.getStock()%>" required></td><td><select form="<%=f%>" name="categoryId"><%for(Category c:cs){%><option value="<%=c.getId()%>" <%=c.getId()==p.getCategoryId()?"selected":""%>><%=c.getName()%></option><%}%></select></td><td>
<form id="<%=f%>" class="inline" action="<%=request.getContextPath()%>/admin-products" method="post"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<%=p.getId()%>"><button>Save</button></form>
<form class="inline" action="<%=request.getContextPath()%>/admin-products" method="post" onsubmit="return confirm('Delete this product?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<%=p.getId()%>"><button>Delete</button></form></td></tr><%}%></table></body></html>
