<%@ page contentType="text/html;charset=UTF-8" %>
<%@ page import="java.util.List,model.User,model.Role" %>
<% User me=(User)session.getAttribute("user"); if(me==null||me.getRole()!=Role.ADMIN){response.sendRedirect(request.getContextPath()+"/login.jsp");return;} List<User> us=(List<User>)request.getAttribute("users"); String err=request.getParameter("error"); %>
<!doctype html><html><head><title>Manage Users</title><style>body{font-family:Arial;max-width:1100px;margin:30px auto;padding:20px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ddd;padding:8px}input,select{padding:6px}.inline{display:inline}</style></head><body>
<h1>Manage Users</h1><p><a href="<%=request.getContextPath()%>/admin.jsp">← Admin</a></p><%if(err!=null){%><p style="color:red"><%=err%></p><%}%>
<h2>Add User</h2><form action="<%=request.getContextPath()%>/admin-users" method="post"><input type="hidden" name="action" value="add"><input name="username" placeholder="Username" required><input name="password" placeholder="Password" required><select name="role"><option>CUSTOMER</option><option>WAREHOUSE</option><option>ADMIN</option></select><button>Add User</button></form>
<table><tr><th>ID</th><th>Username</th><th>Password</th><th>Role</th><th>Actions</th></tr><%for(User x:us){String f="u"+x.getId();%><tr><td><%=x.getId()%></td><td><input form="<%=f%>" name="username" value="<%=x.getUsername()%>" required></td><td><input form="<%=f%>" name="password" value="<%=x.getPassword()%>" required></td><td><select form="<%=f%>" name="role"><option <%=x.getRole()==Role.CUSTOMER?"selected":""%>>CUSTOMER</option><option <%=x.getRole()==Role.WAREHOUSE?"selected":""%>>WAREHOUSE</option><option <%=x.getRole()==Role.ADMIN?"selected":""%>>ADMIN</option></select></td><td>
<form id="<%=f%>" class="inline" action="<%=request.getContextPath()%>/admin-users" method="post"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<%=x.getId()%>"><button>Save</button></form>
<%if(x.getId()!=me.getId()){%><form class="inline" action="<%=request.getContextPath()%>/admin-users" method="post" onsubmit="return confirm('Delete this user?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<%=x.getId()%>"><button>Delete</button></form><%}%></td></tr><%}%></table></body></html>
